# -*- coding: utf-8 -*-
"""stremlit_aviones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woQmfP8of-9Sq2F73uKWzjn_MX8o7yOI
"""

# prompt: creame un stremlit que pueda mostrar mi base de datos

pf = pd.read_csv('STRIKE_REPORTS')
pf